services:
  - type: web
    name: cyberx_bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    healthCheckPath: / # Отключаем проверку порта